Add zero conf support
hsjoberg/dunder-lsp pull request #34
Opened 2023-07-17 18:43 UTC by niteshbalusu11

Signed-off-by: Nitesh Balusu <84944042+niteshbalusu11@users.noreply.github.com>

Added dev dependencies of typescript, concurrently and nodemon

Updated protos to lnd v0.16.4

Added zero conf support.

Channel open flow first attempts zero conf two times with a timeout of 4s.

If zero conf fails, then a regular open is attempted twice with a 4s timeout.

2023-07-25 15:29 UTC, hsjoberg requested changes
Code looks good!

I would to have the ability to disable zero conf openings. Please add a config for it.

See:
`config/default.config_TEMPLATE`
`src/utils/common.ts` (bottom)

2023-07-25 15:29 UTC, hsjoberg commented on src/utils/lnd-api.ts
> +    commitmentType: 3,
```suggestion
    commitmentType: lnrpc.CommitmentType.ANCHORS,
```

2023-07-25 17:45 UTC, niteshbalusu11 commented
Ok sure.

2023-07-26 20:58 UTC, hsjoberg approved these changes
Looks good to me. ✅ 

Add the config to `config/test.json` too. Also needs rebase.

2023-07-26 21:03 UTC, niteshbalusu11 commented
Fixed

2023-07-27 09:46 UTC, merged